Avalanche\Bundle\SitemapBundle\Sitemap\Url:
    type: document
    repositoryClass: Avalanche\Bundle\SitemapBundle\Document\UrlRepository
    indexes:
        - { keys: { loc: 1}, options: { unique: 1 } }
        - { keys: { lastmod: 1}, options: {} }
        - { keys: { images.loc: 1 }, options: {} }
    fields:
        id:
            id: true
            type: id
            strategy: auto
        loc:
            type: string
        lastmod:
            type: date
        changefreq:
            type: string
        priority:
            type: string
    embedMany:
        images:
            targetDocument: Avalanche\Bundle\SitemapBundle\Sitemap\Url\Image
