Avalanche\Bundle\SitemapBundle\Sitemap\Url\Image:
    type: embeddedDocument
    indexes:
        - { keys: { loc: 1 }, options: {} }
    fields:
        loc:
            type: string
        caption:
            type: string
        geoLocation:
            type: string
        title:
            type: string
        license:
            type: string
